# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2f8fe0f1306566ef63e185918d6efed90c0f30fe3afc1bcd3afd90dc2f9f1c8861aeb26b0cbebaed66b7066efdb17815eed334e7be9044881bb6e757b76b6a0
  api_v1: dda5d4a458c566c24e1dc2608b58f3fc375a58862515e916ef7d8350cd155800

test:
  secret_key_base: c78045d87f4555d02e233f74bac1c1d1f98afc0a20bd487644874b238a8aafe89a25b8eb6eedd61e3391d9444ac7eabea6edfac9406638e7b5f06209d2b83ddb
  api_v1: dda5d4a458c566c24e1dc2608b58f3fc375a58862515e916ef7d8350cd155800

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["PROD_SECRET_KEY_BASE"] %>
  api_v1: dda5d4a458c566c24e1dc2608b58f3fc375a58862515e916ef7d8350cd155800
